language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
script: jekyll build && htmlproofer --assume-extension ./_site
